package net.java.truelicense.maven.plugin;

import net.java.truelicense.maven.plugin.GenerateSourcesMojo.TemplateSet;

/**
 * Determines how the directory with the files generated by merging the
 * template files with the Velocity context gets added to the maven project.
 *
 * @see GenerateSourcesMojo#generateSourcesStrategy()
 * @author Christian Schlichtherle
 */
public enum GenerateSourcesStrategy {

    mainSources {
        void updateProjectFrom(TemplateSet templateSet) {
            templateSet.addMergeDirectoryToCompileSourceRoot();
        }
    },

    testSources {
        void updateProjectFrom(TemplateSet templateSet) {
            templateSet.addMergeDirectoryToTestCompileSourceRoot();
        }
    };

    abstract void updateProjectFrom(TemplateSet templateSet);
}
