/*
 * Copyright (C) 2005-2015 Schlichtherle IT Services.
 * All rights reserved. Use is subject to license terms.
 */

package org.truelicense.maven.plugin;

import org.truelicense.maven.plugin.GenerateSourcesMojo.TemplateSet;

/**
 * Determines how the directory with the files generated by merging the
 * template files with the Velocity context gets added to the maven project.
 *
 * @see GenerateSourcesMojo#generateSourcesStrategy()
 * @author Christian Schlichtherle
 */
public enum GenerateSourcesStrategy {

    mainSources {
        void updateProjectFrom(TemplateSet templateSet) {
            templateSet.addMergeDirectoryToCompileSourceRoot();
        }
    },

    testSources {
        void updateProjectFrom(TemplateSet templateSet) {
            templateSet.addMergeDirectoryToTestCompileSourceRoot();
        }
    };

    abstract void updateProjectFrom(TemplateSet templateSet);
}
